name: GIUTGIOT
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0


  ## 20240731 SHJ
    ## stt,tts
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  permission_handler: ^10.2.0
    ## postural analysis
  sensors: ^2.0.0
  shared_preferences: ^2.0.6
  tflite_flutter: ^0.10.1
  syncfusion_flutter_sliders: ^19.2.55

  connectivity_plus: ^1.0.6
  ## socket_io_client: ^2.0.0-beta.5
  #  screen: ^0.0.5
  ## python Flast
  http:
  cupertino_icons: ^1.0.6
  flutter_sound: ^9.9.5
  path_provider: ^2.0.9
  ## SHJ FIN

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  ## 20240802 SHJ
  ## 자세 모델

  # 24.08.03 JJY
  # 백그라운드 배경 화면 적용 완료
  # 모든 파일에 접근할 수 있도록 활성화 (예정)
  assets:
    - assets/model/posture_analysis.tflite
    - assets/background/bg_hourglass.gif
    - assets/background/bg.gif
    - assets/background/hourglass.png
    - assets/icon/google_icon.png
    - assets/icon/naver_icon.png
    - assets/icon/kakao_icon.png
    - assets/icon/sandhour.gif
  ## SHJ FIN
    - assets/background/bg.gif
    - assets/background/hourglass.png
