name: GIUTGIOT
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0


  ## 20240731 SHJ
    ## stt,tts
  speech_to_text: ^6.1.1
  flutter_tts: ^3.6.3
  permission_handler: ^10.2.0
    ## postural analysis
  sensors: ^2.0.0
  shared_preferences: ^2.0.6
  tflite_flutter: ^0.10.1
  syncfusion_flutter_sliders: ^19.2.55

  connectivity_plus: ^1.0.6
  ## socket_io_client: ^2.0.0-beta.5
  #  screen: ^0.0.5
  ## python Flast
  http:
  cupertino_icons: ^1.0.6
  flutter_sound: ^9.9.5
  path_provider: ^2.0.9
  flame: ^1.18.0
  forge2d: ^0.13.0
  flame_forge2d: ^0.18.1
  ## SHJ FIN
  ## wave
  siri_wave: ^2.0.0+1
  ##bluetooth
  flutter_blue: ^0.8.0
  flutter_blue_plus: ^1.32.11

  ## splash
#  flutter_native_splash: ^2.4.1
#
#flutter_native_splash:
#  color: "#42a5f5"
#  android_12: true



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^0.22.0

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  ## 20240802 SHJ
  ## 자세 모델

  # 24.08.03 JJY
  # 백그라운드 배경 화면 적용 완료
  # 모든 파일에 접근할 수 있도록 활성화 (예정)
  assets:
    - assets/model/posture_analysis.tflite
    # 아이콘 폴더 내 모든 이미지 접근 가능 - 정진영 (24.08.04)
    - assets/background/
    - assets/icon/
    - assets/clothes/
    - assets/test.json

    - assets/test_icon/upclothes.png
    - assets/test_icon/downclothes.png
    - assets/test_icon/long_upclothes.png
    - assets/test_icon/short_downclothes.png


    # top
    - assets/test_icon/top/knit.webp
    - assets/test_icon/top/muji.webp
    - assets/test_icon/top/shirt.webp
    - assets/test_icon/top/shirt2.webp
    - assets/test_icon/top/mujiTshirt.webp

    # bottom
    - assets/test_icon/bottom/p_jean.png
    - assets/test_icon/bottom/p_cotton.png
    - assets/test_icon/bottom/p_slacks.png
    - assets/test_icon/bottom/skirt.png
    - assets/test_icon/bottom/p_cargo.png
    - assets/test_icon/bottom/p_training.png

    # pattern
    - assets/test_icon/pattern/dot.webp
    - assets/test_icon/pattern/flower.webp
    - assets/test_icon/pattern/muji.webp
    - assets/test_icon/pattern/stripe.webp
    - assets/test_icon/pattern/check.webp

    - assets/today_clothes.json

    # custom
    - assets/svgfile/


  ## SHJ FIN

